### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by MeltyPlayer** [SceneGate/Ekona#30]
These SceneGate libraries are awesome! I'm currently working on a generalized model-ripping tool (https://github.com/MeltyPlayer/FinModelUtility), and I was hoping to pull these in to make it easier to extract files from DS/3DS ROMs. The READMEs for these projects link to Nuget packages, though it looks like they're either dead links or the associated Nuget packages haven't been set up yet.

Would you be able to set up Nuget packages for these libraries at some point?

**Comment by pleonex** [comment]
Thanks a lot!
I will release the nugets to nuget.org with the first non-preview release (I just need to finish some docs for Yarhl v4.0 first). You can use the latest preview version with nuget packages from the preview feed in [Azure DevOps Feed](https://dev.azure.com/SceneGate/SceneGate/_artifacts/feed/SceneGate-Preview)
You can find details in the [usage](https://github.com/SceneGate/Ekona/#usage) section of the readme but basically you need to create a file named `nuget.config` in the same directory as your `.sln` file with this content:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear/>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="SceneGate-Preview" value="https://pkgs.dev.azure.com/SceneGate/SceneGate/_packaging/SceneGate-Preview/nuget/v3/index.json" />
  </packageSources>
  <packageSourceMapping>
    <packageSource key="nuget.org">
      <package pattern="*" />
    </packageSource>
    <packageSource key="SceneGate-Preview">
      <package pattern="Yarhl*" />
      <package pattern="Texim*" />
      <package pattern="SceneGate*" />
    </packageSource>
  </packageSourceMapping>
</configuration>
```

Then restart your IDE (e.g. Visual Studio) and the nugets should show in the list of the feed `SceneGate-Preview`
![imagen](https://github.com/SceneGate/Ekona/assets/3107481/c24fbbd5-c8e6-45d7-aad5-167c425cae09)

**Comment by MeltyPlayer** [comment]
> You can use the latest preview version with nuget packages from the preview feed in [Azure DevOps Feed](https://dev.azure.com/SceneGate/SceneGate/_artifacts/feed/SceneGate-Preview)

Ah, sounds good, thank you so much!
